#!/usr/bin/env bash
# Writes ios/Config/Version.xcconfig from version.json.
#
#   BUILD_NUMBER  - the build number (Codemagic sets this automatically and
#                   increments it on every build of the workflow). Defaults to 1
#                   for a local/compile-check build.
#   BUNDLE_ID     - optional override of version.json's bundleId.
#
# version.json is the ONLY place the iOS marketing version is edited. It is
# independent of the Android project's own version file.
set -euo pipefail
cd "$(dirname "$0")/.."

read_json() { node -e "process.stdout.write(String(require('./version.json')['$1']))"; }

MARKETING_VERSION="$(read_json marketingVersion)"
BUNDLE_ID="${BUNDLE_ID:-$(read_json bundleId)}"
BUILD_NUMBER="${BUILD_NUMBER:-1}"

if ! [[ "$MARKETING_VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
  echo "version.json marketingVersion must be MAJOR.MINOR.PATCH, got '$MARKETING_VERSION'" >&2; exit 1
fi
if ! [[ "$BUILD_NUMBER" =~ ^[0-9]+$ ]]; then
  echo "BUILD_NUMBER must be a positive integer, got '$BUILD_NUMBER'" >&2; exit 1
fi

cat > ios/Config/Version.xcconfig <<XC
// GENERATED by scripts/set-version.sh from ../../version.json - do not edit by hand.
// Checked in with the local defaults so the project opens and builds without
// running the script first; CI regenerates it with the real build number.
MARKETING_VERSION = ${MARKETING_VERSION}
CURRENT_PROJECT_VERSION = ${BUILD_NUMBER}
PRODUCT_BUNDLE_IDENTIFIER = ${BUNDLE_ID}
XC

echo "ScamAware-iOS version ${MARKETING_VERSION} build ${BUILD_NUMBER} (${BUNDLE_ID})"
