#!/usr/bin/env bash
#
# Compiles the Android module and runs its JVM unit tests without the Android SDK.
#
# WHY THIS EXISTS
# `dl.google.com` is unreachable from the sandbox this repository is developed in, so neither the
# Android SDK nor AGP can be downloaded and `./gradlew` cannot run there at all. The real build is
# done by CI (.github/workflows/build-android.yml) and nothing here replaces it. What this replaces
# is the gap in between: an over-the-air update mechanism whose state machine can only be exercised
# on a phone is a state machine nobody exercises, and every test under app/src/test/ is written to
# run on a plain JVM precisely so that is not the case.
#
# HOW IT SUBSTITUTES FOR THE SDK
#   android.jar        org.robolectric:android-all, from Maven Central, which is a real android.jar
#                      with real method bodies. Gradle's own unit tests use a *mockable* android.jar
#                      whose methods return defaults (unitTests.returnDefaultValues), so this is if
#                      anything the stricter of the two.
#   androidx.webkit    a two-class compile-only stub in tools/stubs/. It lives on Google's Maven
#                      repository, which is the one that is unreachable. Nothing in the tests calls
#                      into it - WebBundleResponder is where the serving logic actually is.
#   JJSDK              app/libs/jjsdk.aar, restored from this repository's own history by
#                      settings.gradle; classes.jar is unzipped out of it here.
#   org.json           the real implementation, exactly as app/build.gradle puts it on the test
#                      classpath for the same reason.
#
# Usage:  android/tools/run-jvm-tests.sh [TestClassName ...]
# With no arguments it runs every *Test class under app/src/test/.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MODULE="$(cd "$HERE/.." && pwd)/app"
LIB="$HERE/lib"
OUT="$HERE/build"

MAVEN="${MAVEN_REPO:-https://repo1.maven.org/maven2}"
ANDROID_ALL="android-all-15-robolectric-12650502.jar"

fetch() { # <relative maven path> <local filename>
  [ -f "$LIB/$2" ] && return 0
  echo "→ fetching $2"
  mkdir -p "$LIB"
  curl -sSLf -o "$LIB/$2" "$MAVEN/$1"
}

fetch "junit/junit/4.13.2/junit-4.13.2.jar" "junit-4.13.2.jar"
fetch "org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar" "hamcrest-core-1.3.jar"
fetch "org/json/json/20231013/json-20231013.jar" "json-20231013.jar"
fetch "org/robolectric/android-all/15-robolectric-12650502/$ANDROID_ALL" "$ANDROID_ALL"

# The vendor SDK is stored in git history rather than as a working-tree binary; settings.gradle
# restores it for a Gradle build, and this does the same for a javac one.
if [ ! -s "$MODULE/libs/jjsdk.aar" ] || [ "$(stat -c%s "$MODULE/libs/jjsdk.aar")" -lt 1000000 ]; then
  echo "→ restoring app/libs/jjsdk.aar from git history"
  mkdir -p "$MODULE/libs"
  git -C "$MODULE/../.." cat-file blob ca510d9dc8680423da77be49aeb89eaa788e1bea > "$MODULE/libs/jjsdk.aar"
fi
if [ ! -f "$LIB/jjsdk-classes.jar" ]; then
  echo "→ unpacking JJSDK classes.jar"
  unzip -p "$MODULE/libs/jjsdk.aar" classes.jar > "$LIB/jjsdk-classes.jar"
fi

rm -rf "$OUT"
mkdir -p "$OUT/main" "$OUT/test"

# TWO classpaths, because AGP compiles the two source sets against two different org.json builds
# and the difference is not cosmetic: on Android, JSONException is a CHECKED exception and
# JSONObject.toString(int) declares it; in the reference build on the unit-test classpath it is a
# RuntimeException and toString(int) does not. Code that compiles against one and not the other is
# a build failure that only shows up on whichever side happens not to be run first - which is
# exactly how a `toString(2)` in main/ passed here and failed in CI.
#
#   MAIN_CP  android-all only, so main/ is compiled against Android's org.json, as AGP does.
#   TEST_CP  the reference org.json in front, mirroring app/build.gradle's testImplementation,
#            which exists because Gradle's mockable android.jar stubs org.json out entirely.
MAIN_CP="$LIB/jjsdk-classes.jar:$LIB/$ANDROID_ALL"
TEST_CP="$LIB/json-20231013.jar:$LIB/junit-4.13.2.jar:$LIB/hamcrest-core-1.3.jar:$MAIN_CP"

# aapt generates R.java from res/, and aapt is part of the SDK. The app references exactly three
# resources, so the stub is generated here from the source itself rather than written down: a
# resource added tomorrow gets a field without anybody remembering this file exists.
echo "→ generating an R stub from the resources the sources reference"
mkdir -p "$OUT/gen/com/bigxreality/jorjinverifier"
{
  echo "package com.bigxreality.jorjinverifier;"
  echo "/** Generated by tools/run-jvm-tests.sh in place of aapt's R.java. Never committed. */"
  echo "public final class R {"
  grep -rhoE 'R\.[a-z]+\.[A-Za-z0-9_]+' "$MODULE/src/main/java" | sort -u \
    | awk -F. '{ print $2, $3 }' | sort -u \
    | awk '{ if ($1 != last) { if (last != "") print "  }"; print "  public static final class " $1 " {"; last = $1 } \
             print "    public static final int " $2 " = " (++n) ";" } \
           END { if (last != "") print "  }" }'
  echo "}"
} > "$OUT/gen/com/bigxreality/jorjinverifier/R.java"

# BuildConfig is generated by AGP, not aapt, and the app reads SHELL_VERSION out of it. The value
# comes from release/versions.json - the same file app/build.gradle reads - so a stub with a
# made-up version would let a mismatch through exactly where ShellVersionTest is looking for one.
VERSIONS="$MODULE/../../release/versions.json"
SHELL_VERSION="$(python3 -c 'import json,sys;print(json.load(open(sys.argv[1]))["shellVersion"])' "$VERSIONS")"
SHELL_VERSION_CODE="$(python3 -c 'import json,sys;print(json.load(open(sys.argv[1]))["shellVersionCode"])' "$VERSIONS")"
cat > "$OUT/gen/com/bigxreality/jorjinverifier/BuildConfig.java" <<EOF
package com.bigxreality.jorjinverifier;
/** Generated by tools/run-jvm-tests.sh in place of AGP's BuildConfig. Never committed. */
public final class BuildConfig {
    public static final String SHELL_VERSION = "$SHELL_VERSION";
    public static final String VERSION_NAME = "$SHELL_VERSION+local";
    public static final int VERSION_CODE = $SHELL_VERSION_CODE;
    public static final boolean DEBUG = false;
    public static final String APPLICATION_ID = "com.bigxreality.jorjinverifier";
}
EOF

echo "→ compiling main sources"
find "$MODULE/src/main/java" "$HERE/stubs" "$OUT/gen" -name '*.java' > "$OUT/main.args"
# --release 8 for the app sources, matching compileOptions in app/build.gradle, so a JDK 21 API
# that AGP would reject cannot creep in unnoticed. android-all sits on the ordinary classpath
# rather than the bootclasspath: it carries copies of java.* too, and the JDK's own must win.
javac -nowarn -encoding UTF-8 --release 8 \
  -cp "$MAIN_CP" -d "$OUT/main" @"$OUT/main.args" 2>&1 | grep -v "^Note:\|^warning:\|bootstrap class path" || true
[ -f "$OUT/main/com/bigxreality/jorjinverifier/MainActivity.class" ] \
  || { echo "main sources did not compile"; exit 1; }

# AGP compiles test/ against android.jar, which carries java.* and android.* and nothing else -
# so a JDK-only package resolves on this desktop JVM and fails in CI. That is not hypothetical:
# com.sun.net.httpserver in OtaUpdaterTest compiled here and failed compileDebugUnitTestJavaWithJavac
# with "cannot find symbol: HttpServer". android-all has no java.* at all, so it cannot be put on a
# bootclasspath to reproduce that faithfully; this grep is the cheap check that catches the class of
# mistake instead.
echo "→ checking the tests use nothing outside android.jar"
FORBIDDEN="$(grep -rhoE '^import (com\.sun|jdk|sun)\.[A-Za-z0-9_.]+;' "$MODULE/src" || true)"
if [ -n "$FORBIDDEN" ]; then
  echo "these packages are not on Android's compile classpath and will fail in CI:"
  echo "$FORBIDDEN" | sort -u | sed 's/^/  /'
  exit 1
fi

echo "→ compiling tests"
find "$MODULE/src/test/java" -name '*.java' > "$OUT/test.args"
# The tests are not shipped, so they compile against this JDK. They use com.sun.net.httpserver to
# stand up a real update server, which is how "the phone downloads over HTTP" is a thing a test can
# actually do rather than something mocked into agreeing with itself.
javac -nowarn -encoding UTF-8 \
  -cp "$OUT/main:$TEST_CP" -d "$OUT/test" @"$OUT/test.args" 2>&1 | grep -v "^Note:" || true

if [ "$#" -gt 0 ]; then
  CLASSES=()
  for name in "$@"; do CLASSES+=("com.bigxreality.jorjinverifier.$name"); done
else
  # Every compiled *Test, in whichever package it ended up in.
  mapfile -t CLASSES < <(cd "$OUT/test" && find . -name '*Test.class' \
    | sed 's|^\./||; s|\.class$||; s|/|.|g' | sort)
fi

echo "→ running ${#CLASSES[@]} test classes"
# The module directory as the working directory, which is what Gradle uses and what the tests that
# read files out of the repository (AppIdentityTest, ProductionStartupTest) resolve against.
cd "$MODULE"
java -Dfile.encoding=UTF-8 -cp "$OUT/test:$OUT/main:$TEST_CP" org.junit.runner.JUnitCore "${CLASSES[@]}"
